# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_pi <- function(X, gammak) {
    .Call('_ZINB_c_pi', PACKAGE = 'ZINB', X, gammak)
}

c_mu <- function(X, betak) {
    .Call('_ZINB_c_mu', PACKAGE = 'ZINB', X, betak)
}

Qik <- function(pi_k, mu_k, y_k, thetak) {
    .Call('_ZINB_Qik', PACKAGE = 'ZINB', pi_k, mu_k, y_k, thetak)
}

l1_theta <- function(z_k, y_k, mu_k, thetak) {
    .Call('_ZINB_l1_theta', PACKAGE = 'ZINB', z_k, y_k, mu_k, thetak)
}

score <- function(X, y_k, z_k, mu_k, pi_k, thetak) {
    .Call('_ZINB_score', PACKAGE = 'ZINB', X, y_k, z_k, mu_k, pi_k, thetak)
}

l2_theta <- function(z_k, y_k, mu_k, thetak) {
    .Call('_ZINB_l2_theta', PACKAGE = 'ZINB', z_k, y_k, mu_k, thetak)
}

In <- function(X, y_k, z_k, mu_k, pi_k, gammak, thetak) {
    .Call('_ZINB_In', PACKAGE = 'ZINB', X, y_k, z_k, mu_k, pi_k, gammak, thetak)
}

dznbinom <- function(x, size, prob, infl) {
    .Call('_ZINB_dznbinom', PACKAGE = 'ZINB', x, size, prob, infl)
}

par_EM <- function(X, y_k, tol = 1e-3, maxIter = 5000L, inflation = TRUE, initial = NULL) {
    .Call('_ZINB_par_EM', PACKAGE = 'ZINB', X, y_k, tol, maxIter, inflation, initial)
}

LRT1G <- function(X, y_k, tol = 1e-3, maxIter = 5000L, inflation = TRUE, initial = NULL) {
    .Call('_ZINB_LRT1G', PACKAGE = 'ZINB', X, y_k, tol, maxIter, inflation, initial)
}

LRTnG <- function(X, Y, inflation, tol = 1e-3, maxIter = 5000L, initial = NULL) {
    .Call('_ZINB_LRTnG', PACKAGE = 'ZINB', X, Y, inflation, tol, maxIter, initial)
}

